# Generated by Django 5.2 on 2025-04-09 08:40

import django.contrib.gis.db.models.fields
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('ref', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('name_desc', django.contrib.postgres.search.SearchVectorField(verbose_name=['name', 'description'])),
            ],
            options={
                'indexes': [models.Index(fields=['name_desc'], name='product_pro_name_de_5f2721_idx')],
            },
        ),
    ]
