# Generated by Django 5.2 on 2025-04-09 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(default=uuid.UUID('1f015432-82bb-62f9-9e3d-974ecaaa2e09'), max_length=255, unique=True),
        ),
    ]
