# Generated by Django 5.2 on 2025-04-09 13:15

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(default=uuid.UUID('1f01544b-c51e-6497-9d66-9195eba07543'), max_length=255, unique=True),
        ),
    ]
