# Generated by Django 5.2 on 2025-04-09 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_geolocation_alter_product_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(default=uuid.UUID('1f01547c-7de6-6ea4-bf64-b189a894f61a'), max_length=255, unique=True),
        ),
    ]
